version: '3.8'

services:
  prx:
    build:
      # - separator means, a default value 1000
      # running echo $UID and echo $GID. If you see values for both, great!
      # If you don't, you'll need to export them by running the following command:
      # export UID=$(id -u) && export GID=$(id -g)
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
      context: ./
      dockerfile: ./Dockerfile
    container_name: proxies
    user: ${UID:-1000}:${GID:-1000}
    restart: always
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
      - ./xdebug/tmp:/xdebug/tmp
      - ./xdebug/coverage:/opt/phpstorm-coverage
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/
    networks:
      - app-network
  db:
    image: mysql:5.7.22
    container_name: db
    user: ${UID:-1000}:${GID:-1000}
    restart: always
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
      - ./mysql/configs:/etc/mysql/conf.d
      - ./mysql/logs:/var/lib/mysql-logs
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
